name: Go Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: |
        go get github.com/schollz/progressbar/v3
        go get golang.org/x/sys/windows

    - name: Build
      run: go build -v -o fba_ads-FileRemover.exe

    - name: Create ZIP Archive
      run: |
        powershell Compress-Archive -Path fba_ads-FileRemover.exe -DestinationPath fba_ads-FileRemover.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: fba_ads-FileRemover
        path: fba_ads-FileRemover.zip

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: fba_ads-FileRemover.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}